# Generated by Django 3.1.4 on 2021-01-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210103_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producr_name',
            new_name='product_name',
        ),
    ]
